
pydist$d_WR1 = sqrt(((pydist$x_WR1 - pydist$x)^2) + ((pydist$y_WR1 - pydist$y)^2))
pydist$d_WR2 = sqrt(((pydist$x_WR2 - pydist$x)^2) + ((pydist$y_WR2 - pydist$y)^2))
pydist$d_WR3 = sqrt(((pydist$x_WR3 - pydist$x)^2) + ((pydist$y_WR3 - pydist$y)^2))
pydist$d_WR4 = sqrt(((pydist$x_WR4 - pydist$x)^2) + ((pydist$y_WR4 - pydist$y)^2))
pydist$d_WR5 = sqrt(((pydist$x_WR5 - pydist$x)^2) + ((pydist$y_WR5 - pydist$y)^2))
pydist$d_QB1 = sqrt(((pydist$x_QB1 - pydist$x)^2) + ((pydist$y_QB1 - pydist$y)^2))
pydist$d_QB2 = sqrt(((pydist$x_QB2 - pydist$x)^2) + ((pydist$y_QB2 - pydist$y)^2))
pydist$d_TE1 = sqrt(((pydist$x_TE1 - pydist$x)^2) + ((pydist$y_TE1 - pydist$y)^2))
pydist$d_TE2 = sqrt(((pydist$x_TE2 - pydist$x)^2) + ((pydist$y_TE2 - pydist$y)^2))
pydist$d_TE3 = sqrt(((pydist$x_TE3 - pydist$x)^2) + ((pydist$y_TE3 - pydist$y)^2))
pydist$d_TE4 = sqrt(((pydist$x_TE4 - pydist$x)^2) + ((pydist$y_TE4 - pydist$y)^2))
pydist$d_RB1 = sqrt(((pydist$x_RB1 - pydist$x)^2) + ((pydist$y_RB1 - pydist$y)^2))
pydist$d_RB2 = sqrt(((pydist$x_RB2 - pydist$x)^2) + ((pydist$y_RB2 - pydist$y)^2))
pydist$d_RB3 = sqrt(((pydist$x_RB3 - pydist$x)^2) + ((pydist$y_RB3 - pydist$y)^2))
pydist$d_FB1 = sqrt(((pydist$x_FB1 - pydist$x)^2) + ((pydist$y_FB1 - pydist$y)^2))

# head(pydist)

mdst = 7

pydist = pydist %>%
  mutate(SGG = ifelse(d_WR1 < mdst | d_WR2 < mdst | d_WR3 < mdst | d_WR4 < mdst | d_WR5 < mdst | d_TE1 < mdst |
                        d_TE2 < mdst | d_TE3 < mdst | d_TE4 < mdst | d_RB1 < mdst | d_RB2 < mdst | d_RB3 < mdst | d_FB1 < mdst, 
                      ifelse((QOSi - QOSi_prev) > 0.002,
                             ifelse((QOSi - QOSi_prev3) > 0.008, 1, 0),0),0))

pydist = pydist %>%
  mutate(SOL = ifelse(d_WR1 < mdst | d_WR2 < mdst | d_WR3 < mdst | d_WR4 < mdst | d_WR5 < mdst |  d_TE1 < mdst |
                        d_TE2 < mdst | d_TE3 < mdst | d_TE4 < mdst | d_RB1 < mdst | d_RB2 < mdst | d_RB3 < mdst | d_FB1 < mdst, 
                      ifelse((QOSi - QOSi_prev) < -0.002,
                             ifelse((QOSi - QOSi_prev3) < -0.008, 1, 0),0),0))


pydist = pydist %>%
  group_by(gameId, playId, frameId, nflId) %>%
  mutate(d_min1 = sort(c(d_WR1, d_WR2, d_WR3, d_WR4, d_WR5, d_TE1, d_TE2, d_TE3, d_TE4, d_RB1, d_RB2, d_RB3, d_FB1))[1],
         d_min2 = sort(c(d_WR1, d_WR2, d_WR3, d_WR4, d_WR5, d_TE1, d_TE2, d_TE3, d_TE4, d_RB1, d_RB2, d_RB3, d_FB1))[2],
         d_min3 = sort(c(d_WR1, d_WR2, d_WR3, d_WR4, d_WR5, d_TE1, d_TE2, d_TE3, d_TE4, d_RB1, d_RB2, d_RB3, d_FB1))[3])

pydist = pydist %>%
  mutate(d_min1 = ifelse(d_min1 > 10, NA, d_min1),
         d_min2 = ifelse(d_min2 > 10, NA, d_min2),
         d_min3 = ifelse(d_min3 > 10, NA, d_min3))


pydist = pydist %>%
  mutate(pos_min1 = ifelse(!is.na(d_WR1) & d_WR1 == d_min1, 'WR1', ifelse(!is.na(d_WR2) & d_WR2 == d_min1, 'WR2', 
                                                                          ifelse(!is.na(d_WR3) & d_WR3 == d_min1, 'WR3', ifelse(!is.na(d_WR4) & d_WR4 == d_min1, 'WR4',
                                                                                                                                ifelse(!is.na(d_WR5) & d_WR5 == d_min1, 'WR5', ifelse(!is.na(d_TE1) & d_TE1 == d_min1, 'TE1',
                                                                                                                                                                                      ifelse(!is.na(d_TE2) & d_TE2 == d_min1, 'TE2', ifelse(!is.na(d_TE3) & d_TE3 == d_min1, 'TE3',
                                                                                                                                                                                                                                            ifelse(!is.na(d_TE4) & d_TE4 == d_min1, 'TE4', ifelse(!is.na(d_RB1) & d_RB1 == d_min1, 'RB1', 
                                                                                                                                                                                                                                                                                                  ifelse(!is.na(d_RB2) & d_RB2 == d_min1, 'RB2', ifelse(!is.na(d_RB3) & d_RB3 == d_min1, 'RB3', 
                                                                                                                                                                                                                                                                                                                                                        ifelse(!is.na(d_FB1) & d_FB1 == d_min1, 'FB1', NA))))))))))))),
         pos_min2 = ifelse(!is.na(d_WR1) & d_WR1 == d_min2, 'WR1', ifelse(!is.na(d_WR2) & d_WR2 == d_min2, 'WR2', 
                                                                          ifelse(!is.na(d_WR3) & d_WR3 == d_min2, 'WR3', ifelse(!is.na(d_WR4) & d_WR4 == d_min2, 'WR4', 
                                                                                                                                ifelse(!is.na(d_WR5) & d_WR5 == d_min2, 'WR5', ifelse(!is.na(d_TE1) & d_TE1 == d_min2, 'TE1', 
                                                                                                                                                                                      ifelse(!is.na(d_TE2) & d_TE2 == d_min2, 'TE2', ifelse(!is.na(d_TE3) & d_TE3 == d_min2, 'TE3',
                                                                                                                                                                                                                                            ifelse(!is.na(d_TE4) & d_TE4 == d_min2, 'TE4', ifelse(!is.na(d_RB1) & d_RB1 == d_min2, 'RB1', 
                                                                                                                                                                                                                                                                                                  ifelse(!is.na(d_RB2) & d_RB2 == d_min2, 'RB2', ifelse(!is.na(d_RB3) & d_RB3 == d_min2, 'RB3', 
                                                                                                                                                                                                                                                                                                                                                        ifelse(!is.na(d_FB1) & d_FB1 == d_min2, 'FB1', NA))))))))))))),
         pos_min3 = ifelse(!is.na(d_WR1) & d_WR1 == d_min3, 'WR1', ifelse(!is.na(d_WR2) & d_WR2 == d_min3, 'WR2', 
                                                                          ifelse(!is.na(d_WR3) & d_WR3 == d_min3, 'WR3', ifelse(!is.na(d_WR4) & d_WR4 == d_min3, 'WR4',
                                                                                                                                ifelse(!is.na(d_WR5) & d_WR5 == d_min3, 'WR5', ifelse(!is.na(d_TE1) & d_TE1 == d_min3, 'TE1',                    
                                                                                                                                                                                      ifelse(!is.na(d_TE2) & d_TE2 == d_min3, 'TE2', ifelse(!is.na(d_TE3) & d_TE3 == d_min3, 'TE3',
                                                                                                                                                                                                                                            ifelse(!is.na(d_TE4) & d_TE4 == d_min3, 'TE4', ifelse(!is.na(d_RB1) & d_RB1 == d_min3, 'RB1', 
                                                                                                                                                                                                                                                                                                  ifelse(!is.na(d_RB2) & d_RB2 == d_min3, 'RB2', ifelse(!is.na(d_RB3) & d_RB3 == d_min3, 'RB3', 
                                                                                                                                                                                                                                                                                                                                                        ifelse(!is.na(d_FB1) & d_FB1 == d_min3, 'FB1', NA)))))))))))))
  )

{
  pydist = pydist %>%
    mutate(nflId_min1 = ifelse(!is.na(d_WR1) & d_WR1 == d_min1, nflId_WR1, ifelse(!is.na(d_WR2) & d_WR2 == d_min1, nflId_WR2, 
                                                                                  ifelse(!is.na(d_WR3) & d_WR3 == d_min1, nflId_WR3, ifelse(!is.na(d_WR4) & d_WR4 == d_min1, nflId_WR4,
                                                                                                                                            ifelse(!is.na(d_WR5) & d_WR5 == d_min1, nflId_WR5, ifelse(!is.na(d_TE1) & d_TE1 == d_min1, nflId_TE1,
                                                                                                                                                                                                      ifelse(!is.na(d_TE2) & d_TE2 == d_min1, nflId_TE2, ifelse(!is.na(d_TE3) & d_TE3 == d_min1, nflId_TE3,
                                                                                                                                                                                                                                                                ifelse(!is.na(d_TE4) & d_TE4 == d_min1, nflId_TE4, ifelse(!is.na(d_RB1) & d_RB1 == d_min1, nflId_RB1, 
                                                                                                                                                                                                                                                                                                                          ifelse(!is.na(d_RB2) & d_RB2 == d_min1, nflId_RB2, ifelse(!is.na(d_RB3) & d_RB3 == d_min1, nflId_RB3, 
                                                                                                                                                                                                                                                                                                                                                                                    ifelse(!is.na(d_FB1) & d_FB1 == d_min1, nflId_FB1, NA))))))))))))),
           nflId_min2 = ifelse(!is.na(d_WR1) & d_WR1 == d_min2, nflId_WR1, ifelse(!is.na(d_WR2) & d_WR2 == d_min2, nflId_WR2,
                                                                                  ifelse(!is.na(d_WR3) & d_WR3 == d_min2, nflId_WR3, ifelse(!is.na(d_WR4) & d_WR4 == d_min2, nflId_WR4,
                                                                                                                                            ifelse(!is.na(d_WR5) & d_WR5 == d_min2, nflId_WR5, ifelse(!is.na(d_TE1) & d_TE1 == d_min2, nflId_TE1,
                                                                                                                                                                                                      ifelse(!is.na(d_TE2) & d_TE2 == d_min2, nflId_TE2, ifelse(!is.na(d_TE3) & d_TE3 == d_min2, nflId_TE3,
                                                                                                                                                                                                                                                                ifelse(!is.na(d_TE4) & d_TE4 == d_min2, nflId_TE4, ifelse(!is.na(d_RB1) & d_RB1 == d_min2, nflId_RB1, 
                                                                                                                                                                                                                                                                                                                          ifelse(!is.na(d_RB2) & d_RB2 == d_min2, nflId_RB2, ifelse(!is.na(d_RB3) & d_RB3 == d_min2, nflId_RB3, 
                                                                                                                                                                                                                                                                                                                                                                                    ifelse(!is.na(d_FB1) & d_FB1 == d_min2, nflId_FB1, NA))))))))))))),
           nflId_min3 = ifelse(!is.na(d_WR1) & d_WR1 == d_min3, nflId_WR1, ifelse(!is.na(d_WR2) & d_WR2 == d_min3, nflId_WR2,
                                                                                  ifelse(!is.na(d_WR3) & d_WR3 == d_min3, nflId_WR3, ifelse(!is.na(d_WR4) & d_WR4 == d_min3, nflId_WR4,
                                                                                                                                            ifelse(!is.na(d_WR5) & d_WR5 == d_min3, nflId_WR5, ifelse(!is.na(d_TE1) & d_TE1 == d_min3, nflId_TE1,
                                                                                                                                                                                                      ifelse(!is.na(d_TE2) & d_TE2 == d_min3, nflId_TE2, ifelse(!is.na(d_TE3) & d_TE3 == d_min3, nflId_TE3,
                                                                                                                                                                                                                                                                ifelse(!is.na(d_TE4) & d_TE4 == d_min3, nflId_TE4, ifelse(!is.na(d_RB1) & d_RB1 == d_min3, nflId_RB1, 
                                                                                                                                                                                                                                                                                                                          ifelse(!is.na(d_RB2) & d_RB2 == d_min3, nflId_RB2, ifelse(!is.na(d_RB3) & d_RB3 == d_min3, nflId_RB3, 
                                                                                                                                                                                                                                                                                                                                                                                    ifelse(!is.na(d_FB1) & d_FB1 == d_min3, nflId_FB1, NA))))))))))))),
           route_min1 = ifelse(!is.na(d_WR1) & d_WR1 == d_min1, route_WR1, ifelse(!is.na(d_WR2) & d_WR2 == d_min1, route_WR2,
                                                                                  ifelse(!is.na(d_WR3) & d_WR3 == d_min1, route_WR3, ifelse(!is.na(d_WR4) & d_WR4 == d_min1, route_WR4,
                                                                                                                                            ifelse(!is.na(d_WR5) & d_WR5 == d_min1, route_WR5, ifelse(!is.na(d_TE1) & d_TE1 == d_min1, route_TE1,
                                                                                                                                                                                                      ifelse(!is.na(d_TE2) & d_TE2 == d_min1, route_TE2, ifelse(!is.na(d_TE3) & d_TE3 == d_min1, route_TE3,
                                                                                                                                                                                                                                                                ifelse(!is.na(d_TE4) & d_TE4 == d_min1, route_TE4, ifelse(!is.na(d_RB1) & d_RB1 == d_min1, route_RB1, 
                                                                                                                                                                                                                                                                                                                          ifelse(!is.na(d_RB2) & d_RB2 == d_min1, route_RB2, ifelse(!is.na(d_RB3) & d_RB3 == d_min1, route_RB3, 
                                                                                                                                                                                                                                                                                                                                                                                    ifelse(!is.na(d_FB1) & d_FB1 == d_min1, route_FB1, NA))))))))))))),
           route_min2 = ifelse(!is.na(d_WR1) & d_WR1 == d_min2, route_WR1, ifelse(!is.na(d_WR2) & d_WR2 == d_min2, route_WR2,
                                                                                  ifelse(!is.na(d_WR3) & d_WR3 == d_min2, route_WR3, ifelse(!is.na(d_WR4) & d_WR4 == d_min2, route_WR4,
                                                                                                                                            ifelse(!is.na(d_WR5) & d_WR5 == d_min2, route_WR5, ifelse(!is.na(d_TE1) & d_TE1 == d_min2, route_TE1,
                                                                                                                                                                                                      ifelse(!is.na(d_TE2) & d_TE2 == d_min2, route_TE2, ifelse(!is.na(d_TE3) & d_TE3 == d_min2, route_TE3,
                                                                                                                                                                                                                                                                ifelse(!is.na(d_TE4) & d_TE4 == d_min2, route_TE4, ifelse(!is.na(d_RB1) & d_RB1 == d_min2, route_RB1, 
                                                                                                                                                                                                                                                                                                                          ifelse(!is.na(d_RB2) & d_RB2 == d_min2, route_RB2, ifelse(!is.na(d_RB3) & d_RB3 == d_min2, route_RB3, 
                                                                                                                                                                                                                                                                                                                                                                                    ifelse(!is.na(d_FB1) & d_FB1 == d_min2, route_FB1, NA))))))))))))),
           route_min3 = ifelse(!is.na(d_WR1) & d_WR1 == d_min3, route_WR1, ifelse(!is.na(d_WR2) & d_WR2 == d_min3, route_WR2,
                                                                                  ifelse(!is.na(d_WR3) & d_WR3 == d_min3, route_WR3, ifelse(!is.na(d_WR4) & d_WR4 == d_min3, route_WR4,
                                                                                                                                            ifelse(!is.na(d_WR5) & d_WR5 == d_min3, route_WR5, ifelse(!is.na(d_TE1) & d_TE1 == d_min3, route_TE1,
                                                                                                                                                                                                      ifelse(!is.na(d_TE2) & d_TE2 == d_min3, route_TE2, ifelse(!is.na(d_TE3) & d_TE3 == d_min3, route_TE3,
                                                                                                                                                                                                                                                                ifelse(!is.na(d_TE4) & d_TE4 == d_min3, route_TE4, ifelse(!is.na(d_RB1) & d_RB1 == d_min3, route_RB1, 
                                                                                                                                                                                                                                                                                                                          ifelse(!is.na(d_RB2) & d_RB2 == d_min3, route_RB2, ifelse(!is.na(d_RB3) & d_RB3 == d_min3, route_RB3, 
                                                                                                                                                                                                                                                                                                                                                                                    ifelse(!is.na(d_FB1) & d_FB1 == d_min3, route_FB1, NA))))))))))))),
           QOSi_min1 = ifelse(!is.na(d_WR1) & d_WR1 == d_min1, QOSi_WR1, ifelse(!is.na(d_WR2) & d_WR2 == d_min1, QOSi_WR2, 
                                                                                ifelse(!is.na(d_WR3) & d_WR3 == d_min1, QOSi_WR3, ifelse(!is.na(d_WR4) & d_WR4 == d_min1, QOSi_WR4,
                                                                                                                                         ifelse(!is.na(d_WR5) & d_WR5 == d_min1, QOSi_WR5, ifelse(!is.na(d_TE1) & d_TE1 == d_min1, QOSi_TE1,
                                                                                                                                                                                                  ifelse(!is.na(d_TE2) & d_TE2 == d_min1, QOSi_TE2, ifelse(!is.na(d_TE3) & d_TE3 == d_min1, QOSi_TE3,
                                                                                                                                                                                                                                                           ifelse(!is.na(d_TE4) & d_TE4 == d_min1, QOSi_TE4, ifelse(!is.na(d_RB1) & d_RB1 == d_min1, QOSi_RB1, 
                                                                                                                                                                                                                                                                                                                    ifelse(!is.na(d_RB2) & d_RB2 == d_min1, QOSi_RB2, ifelse(!is.na(d_RB3) & d_RB3 == d_min1, QOSi_RB3, 
                                                                                                                                                                                                                                                                                                                                                                             ifelse(!is.na(d_FB1) & d_FB1 == d_min1, QOSi_FB1, NA))))))))))))),
           QOSi_min2 = ifelse(!is.na(d_WR1) & d_WR1 == d_min2, QOSi_WR1, ifelse(!is.na(d_WR2) & d_WR2 == d_min2, QOSi_WR2, 
                                                                                ifelse(!is.na(d_WR3) & d_WR3 == d_min2, QOSi_WR3, ifelse(!is.na(d_WR4) & d_WR4 == d_min2, QOSi_WR4,
                                                                                                                                         ifelse(!is.na(d_WR5) & d_WR5 == d_min2, QOSi_WR5, ifelse(!is.na(d_TE1) & d_TE1 == d_min2, QOSi_TE1,
                                                                                                                                                                                                  ifelse(!is.na(d_TE2) & d_TE2 == d_min2, QOSi_TE2, ifelse(!is.na(d_TE3) & d_TE3 == d_min2, QOSi_TE3,
                                                                                                                                                                                                                                                           ifelse(!is.na(d_TE4) & d_TE4 == d_min2, QOSi_TE4, ifelse(!is.na(d_RB1) & d_RB1 == d_min2, QOSi_RB1, 
                                                                                                                                                                                                                                                                                                                    ifelse(!is.na(d_RB2) & d_RB2 == d_min2, QOSi_RB2, ifelse(!is.na(d_RB3) & d_RB3 == d_min2, QOSi_RB3, 
                                                                                                                                                                                                                                                                                                                                                                             ifelse(!is.na(d_FB1) & d_FB1 == d_min2, QOSi_FB1, NA))))))))))))),
           QOSi_min3 = ifelse(!is.na(d_WR1) & d_WR1 == d_min3, QOSi_WR1, ifelse(!is.na(d_WR2) & d_WR2 == d_min3, QOSi_WR2, 
                                                                                ifelse(!is.na(d_WR3) & d_WR3 == d_min3, QOSi_WR3, ifelse(!is.na(d_WR4) & d_WR4 == d_min3, QOSi_WR4,
                                                                                                                                         ifelse(!is.na(d_WR5) & d_WR5 == d_min3, QOSi_WR5, ifelse(!is.na(d_TE1) & d_TE1 == d_min3, QOSi_TE1,
                                                                                                                                                                                                  ifelse(!is.na(d_TE2) & d_TE2 == d_min3, QOSi_TE2, ifelse(!is.na(d_TE3) & d_TE3 == d_min3, QOSi_TE3,
                                                                                                                                                                                                                                                           ifelse(!is.na(d_TE4) & d_TE4 == d_min3, QOSi_TE4, ifelse(!is.na(d_RB1) & d_RB1 == d_min3, QOSi_RB1,
                                                                                                                                                                                                                                                                                                                    ifelse(!is.na(d_RB2) & d_RB2 == d_min3, QOSi_RB2, ifelse(!is.na(d_RB3) & d_RB3 == d_min3, QOSi_RB3, 
                                                                                                                                                                                                                                                                                                                                                                             ifelse(!is.na(d_FB1) & d_FB1 == d_min3, QOSi_FB1, NA))))))))))))),
           QOSi_sv_min1 = ifelse(!is.na(d_WR1) & d_WR1 == d_min1, QOSi_sv_WR1, ifelse(!is.na(d_WR2) & d_WR2 == d_min1, QOSi_sv_WR2, 
                                                                                      ifelse(!is.na(d_WR3) & d_WR3 == d_min1, QOSi_sv_WR3, ifelse(!is.na(d_WR4) & d_WR4 == d_min1, QOSi_sv_WR4,
                                                                                                                                                  ifelse(!is.na(d_WR5) & d_WR5 == d_min1, QOSi_sv_WR5, ifelse(!is.na(d_TE1) & d_TE1 == d_min1, QOSi_sv_TE1,
                                                                                                                                                                                                              ifelse(!is.na(d_TE2) & d_TE2 == d_min1, QOSi_sv_TE2, ifelse(!is.na(d_TE3) & d_TE3 == d_min1, QOSi_sv_TE3,
                                                                                                                                                                                                                                                                          ifelse(!is.na(d_TE4) & d_TE4 == d_min1, QOSi_sv_TE4, ifelse(!is.na(d_RB1) & d_RB1 == d_min1, QOSi_sv_RB1, 
                                                                                                                                                                                                                                                                                                                                      ifelse(!is.na(d_RB2) & d_RB2 == d_min1, QOSi_sv_RB2, ifelse(!is.na(d_RB3) & d_RB3 == d_min1, QOSi_sv_RB3, 
                                                                                                                                                                                                                                                                                                                                                                                                  ifelse(!is.na(d_FB1) & d_FB1 == d_min1, QOSi_sv_FB1, NA))))))))))))),
           QOSi_sv_min2 = ifelse(!is.na(d_WR1) & d_WR1 == d_min2, QOSi_sv_WR1, ifelse(!is.na(d_WR2) & d_WR2 == d_min2, QOSi_sv_WR2, 
                                                                                      ifelse(!is.na(d_WR3) & d_WR3 == d_min2, QOSi_sv_WR3, ifelse(!is.na(d_WR4) & d_WR4 == d_min2, QOSi_sv_WR4,
                                                                                                                                                  ifelse(!is.na(d_WR5) & d_WR5 == d_min2, QOSi_sv_WR5, ifelse(!is.na(d_TE1) & d_TE1 == d_min2, QOSi_sv_TE1,
                                                                                                                                                                                                              ifelse(!is.na(d_TE2) & d_TE2 == d_min2, QOSi_sv_TE2, ifelse(!is.na(d_TE3) & d_TE3 == d_min2, QOSi_sv_TE3,
                                                                                                                                                                                                                                                                          ifelse(!is.na(d_TE4) & d_TE4 == d_min2, QOSi_sv_TE4, ifelse(!is.na(d_RB1) & d_RB1 == d_min2, QOSi_sv_RB1, 
                                                                                                                                                                                                                                                                                                                                      ifelse(!is.na(d_RB2) & d_RB2 == d_min2, QOSi_sv_RB2, ifelse(!is.na(d_RB3) & d_RB3 == d_min2, QOSi_sv_RB3, 
                                                                                                                                                                                                                                                                                                                                                                                                  ifelse(!is.na(d_FB1) & d_FB1 == d_min2, QOSi_sv_FB1, NA))))))))))))),
           QOSi_sv_min3 = ifelse(!is.na(d_WR1) & d_WR1 == d_min3, QOSi_sv_WR1, ifelse(!is.na(d_WR2) & d_WR2 == d_min3, QOSi_sv_WR2, 
                                                                                      ifelse(!is.na(d_WR3) & d_WR3 == d_min3, QOSi_sv_WR3, ifelse(!is.na(d_WR4) & d_WR4 == d_min3, QOSi_sv_WR4,
                                                                                                                                                  ifelse(!is.na(d_WR5) & d_WR5 == d_min3, QOSi_sv_WR5, ifelse(!is.na(d_TE1) & d_TE1 == d_min3, QOSi_sv_TE1,
                                                                                                                                                                                                              ifelse(!is.na(d_TE2) & d_TE2 == d_min3, QOSi_sv_TE2, ifelse(!is.na(d_TE3) & d_TE3 == d_min3, QOSi_sv_TE3,
                                                                                                                                                                                                                                                                          ifelse(!is.na(d_TE4) & d_TE4 == d_min3, QOSi_sv_TE4, ifelse(!is.na(d_RB1) & d_RB1 == d_min3, QOSi_sv_RB1, 
                                                                                                                                                                                                                                                                                                                                      ifelse(!is.na(d_RB2) & d_RB2 == d_min3, QOSi_sv_RB2, ifelse(!is.na(d_RB3) & d_RB3 == d_min3, QOSi_sv_RB3, 
                                                                                                                                                                                                                                                                                                                                                                                                  ifelse(!is.na(d_FB1) & d_FB1 == d_min3, QOSi_sv_FB1, NA)))))))))))))
    )
  }

pydist = pydist %>%
  inner_join(targ, by = c('gameId', 'playId')) %>%
  mutate(istarg = ifelse(nflId_min1 == targetNflId, 1, 0))
